apiVersion: apps/v1
kind: Deployment
metadata:
  name: stt
  namespace: aimodel
  labels:
    app: stt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stt
  template:
    metadata:
      labels:
        app: stt
    spec:
      containers:
      - name: stt
        image: mcdodik2008/stt-service
        ports:
        - containerPort: 8000
